apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-sm
  namespace: default
  labels:
    release: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
    - default 
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: nginx-exporter
